# Generated by Django 6.0.5 on 2026-05-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeze',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezes_city', to='core.city'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezes_club', to='core.club'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezes_member', to='core.member'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezes_region', to='core.region'),
        ),
        migrations.CreateModel(
            name='FreezeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_end_date', models.DateField()),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('freeze_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.freeze')),
                ('member_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_logs', to='core.membersubscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFreezePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.freeze')),
                ('member_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_periods', to='core.membersubscription')),
            ],
        ),
    ]
