# Generated by Django 6.0.5 on 2026-05-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_freeze_status_alter_freeze_city_alter_freeze_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
