# Generated by Django 6.0.5 on 2026-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeze',
            name='error_logs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='processed_members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freeze',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freeze',
            name='total_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
