# Generated by Django 6.0.5 on 2026-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freeze_error_logs_freeze_processed_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_freeze_days',
            field=models.PositiveIntegerField(default=30, help_text='Maximum allowed freeze duration in days for this plan'),
        ),
    ]
