# Generated by Django 6.0.5 on 2026-05-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriptionplan_max_freeze_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersubscription',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.member'),
        ),
    ]
