# Generated by Django 6.0.5 on 2026-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membersubscription_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeze',
            name='created_by',
            field=models.CharField(blank=True, default='System', max_length=255, null=True),
        ),
    ]
